services:
  - type: web
    name: studentvault-api
    runtime: node
    plan: free
    rootDir: apps/api
    buildCommand: npm install && npx prisma generate --schema=prisma/schema.prisma && npm run build
    startCommand: node dist/main
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: APP_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
